# deploy/secrets.sh
# SOPS-based secrets initialization
# Source this file - do not execute directly
#
# Requires: lib/output.sh and lib/services.sh sourced first
# Requires: OS, CONFIG_*, LOUD_MODE variables set

# Validate required variables
: "${OS:?Error: OS must be set}"
: "${CONFIG_DB_PASSWORD:?Error: CONFIG_DB_PASSWORD must be set}"

print_header "Step 14: Secrets Configuration (SOPS)"

# Verify age and sops are available
echo -ne "${DIM}${ARROW}${RESET} Checking secrets management tools... "
if ! command -v age &> /dev/null; then
    echo -e "${ERROR}"
    print_error "age not found - required for secrets encryption"
    print_info "Install from: https://github.com/FiloSottile/age"
    exit 1
fi
if ! command -v sops &> /dev/null; then
    echo -e "${ERROR}"
    print_error "sops not found - required for secrets management"
    print_info "Install from: https://github.com/getsops/sops"
    exit 1
fi
echo -e "${CHECKMARK}"

# Create MIRA config directory for age key
AGE_KEY_DIR="$HOME/.config/mira"
AGE_KEY_PATH="${AGE_KEY_DIR}/age.key"
SECRETS_PATH="/opt/mira/app/secrets.enc.yaml"
SOPS_CONFIG_PATH="/opt/mira/app/.sops.yaml"

# Generate age keypair if not exists
echo -ne "${DIM}${ARROW}${RESET} Checking age keypair... "
if [ -f "$AGE_KEY_PATH" ]; then
    echo -e "${CHECKMARK} ${DIM}(already exists)${RESET}"
else
    echo -e "${DIM}(generating)${RESET}"
    mkdir -p "$AGE_KEY_DIR"
    chmod 700 "$AGE_KEY_DIR"
    
    age-keygen > "$AGE_KEY_PATH" 2>/dev/null
    chmod 600 "$AGE_KEY_PATH"
    print_success "Generated age keypair: $AGE_KEY_PATH"
fi

# Extract public key
PUBLIC_KEY=$(grep "^# public key:" "$AGE_KEY_PATH" | sed 's/# public key: //')
if [ -z "$PUBLIC_KEY" ]; then
    print_error "Could not extract public key from age key file"
    exit 1
fi

# Create .sops.yaml configuration
echo -ne "${DIM}${ARROW}${RESET} Creating SOPS configuration... "
cat > "$SOPS_CONFIG_PATH" <<EOF
# SOPS configuration for MIRA secrets
# Generated by: deploy/secrets.sh

creation_rules:
  - path_regex: secrets\\.enc\\.yaml\$
    age: ${PUBLIC_KEY}
EOF
echo -e "${CHECKMARK}"

# Generate JWT secret if not provided
JWT_SECRET=$(openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64)

# Generate MIRA API key
MIRA_API_KEY="mira_$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p)"

# Create secrets template with collected values
echo -ne "${DIM}${ARROW}${RESET} Creating encrypted secrets file... "

# Create temporary unencrypted secrets file
TEMP_SECRETS="/tmp/mira_secrets_$$.yaml"
cat > "$TEMP_SECRETS" <<EOF
providers:
  anthropic_key: "${CONFIG_ANTHROPIC_KEY}"
  anthropic_batch_key: "${CONFIG_ANTHROPIC_BATCH_KEY}"
  provider_key: "${CONFIG_PROVIDER_KEY}"
  kagi_api_key: "${CONFIG_KAGI_KEY:-}"
  openai_embeddings_key: ""
  google_maps_api_key: ""

database:
  service_url: "postgresql://mira_dbuser:${CONFIG_DB_PASSWORD}@localhost:5432/mira_service"
  admin_url: "postgresql://mira_admin:${CONFIG_DB_PASSWORD}@localhost:5432/mira_service"
  username: "mira_dbuser"
  password: "${CONFIG_DB_PASSWORD}"

services:
  valkey_url: "redis://localhost:6379/0"

auth:
  jwt_secret: "${JWT_SECRET}"
  mira_api: "${MIRA_API_KEY}"
EOF

# Encrypt with SOPS
export SOPS_AGE_KEY_FILE="$AGE_KEY_PATH"
if sops -e --filename-override "$SECRETS_PATH" --output "$SECRETS_PATH" "$TEMP_SECRETS" 2>/dev/null; then
    echo -e "${CHECKMARK}"
    chmod 600 "$SECRETS_PATH"
else
    echo -e "${ERROR}"
    print_error "Failed to encrypt secrets file"
    rm -f "$TEMP_SECRETS"
    exit 1
fi

# Clean up temporary file
rm -f "$TEMP_SECRETS"

print_success "Secrets configured with SOPS encryption"
print_info "Age key stored at: $AGE_KEY_PATH"
print_info "Secrets file: $SECRETS_PATH"
print_info "To edit secrets later: python scripts/secrets_cli.py edit"

