# SOPS Secrets Schema - Fail-Fast Validation
#
# This schema defines required and optional secrets for MIRA-OSS.
# All 'required: true' fields MUST exist or the application refuses to start.
#
# Field types:
#   - string: Text value
#   - integer: Numeric value
#   - boolean: true/false
#
# To add a new secret:
#   1. Add the field definition here with type and required flag
#   2. Run 'mira secrets edit' to add the actual value
#   3. Run 'mira secrets check' to validate

providers:
  # Anthropic API key - required for core LLM functionality
  anthropic_key:
    type: string
    required: true

  # Anthropic Batch API key - optional, for batch processing
  anthropic_batch_key:
    type: string
    required: false

  # Alternative provider key (OpenRouter, etc.) - optional
  provider_key:
    type: string
    required: false

  # Kagi search API key - optional, for web search tool
  kagi_api_key:
    type: string
    required: false

  # OpenAI embeddings key - optional, only if using OpenAI embeddings
  openai_embeddings_key:
    type: string
    required: false

  # Google Maps API key - optional, for location tools
  google_maps_api_key:
    type: string
    required: false

database:
  # PostgreSQL service connection URL - required
  service_url:
    type: string
    required: true

  # PostgreSQL admin connection URL (BYPASSRLS) - required
  admin_url:
    type: string
    required: true

  # Database username - required
  username:
    type: string
    required: true

  # Database password - required
  password:
    type: string
    required: true

services:
  # Valkey/Redis URL for caching and sessions - required
  valkey_url:
    type: string
    required: true

auth:
  # JWT secret for API authentication - required
  jwt_secret:
    type: string
    required: true

  # API key for MIRA API access - required
  mira_api:
    type: string
    required: true

