#!/usr/bin/env python3
"""
MIRA Secrets CLI - SOPS-based secrets management.

Commands:
    mira-secrets init   - Generate age keypair and create empty secrets template
    mira-secrets edit   - Edit secrets in $EDITOR (decrypts, edits, re-encrypts)
    mira-secrets check  - Validate secrets configuration without starting MIRA

Usage:
    python scripts/secrets_cli.py init
    python scripts/secrets_cli.py edit
    python scripts/secrets_cli.py check

Or if installed:
    mira-secrets init
    mira-secrets edit
    mira-secrets check
"""

import argparse
import os
import stat
import subprocess
import sys
from pathlib import Path

# Add project root to path for imports
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

# Default paths
DEFAULT_AGE_KEY_PATH = Path.home() / ".config" / "mira" / "age.key"
DEFAULT_SECRETS_PATH = PROJECT_ROOT / "secrets.enc.yaml"
SCHEMA_PATH = PROJECT_ROOT / "clients" / "secrets" / "schema.yaml"


def print_success(msg: str) -> None:
    """Print success message with green checkmark."""
    print(f"✓ {msg}")


def print_error(msg: str) -> None:
    """Print error message with red X."""
    print(f"✗ {msg}", file=sys.stderr)


def print_info(msg: str) -> None:
    """Print info message."""
    print(f"  {msg}")


def check_sops_installed() -> bool:
    """Check if SOPS is installed."""
    try:
        subprocess.run(["sops", "--version"], capture_output=True, check=True)
        return True
    except FileNotFoundError:
        return False


def check_age_installed() -> bool:
    """Check if age is installed."""
    try:
        subprocess.run(["age", "--version"], capture_output=True, check=True)
        return True
    except FileNotFoundError:
        return False


def cmd_init(args: argparse.Namespace) -> int:
    """Initialize secrets: generate age keypair and create encrypted secrets template."""
    print("Initializing MIRA secrets management...\n")

    # Check prerequisites
    if not check_age_installed():
        print_error("'age' not found. Install from: https://github.com/FiloSottile/age")
        return 1

    if not check_sops_installed():
        print_error("'sops' not found. Install from: https://github.com/getsops/sops")
        return 1

    print_success("Prerequisites found (age, sops)")

    # Generate age keypair if not exists
    age_key_path = Path(args.age_key_path)

    if age_key_path.exists() and not args.force:
        print_info(f"Age key already exists: {age_key_path}")
        print_info("Use --force to regenerate (WARNING: will invalidate existing secrets)")
    else:
        # Create parent directory with secure permissions
        age_key_path.parent.mkdir(parents=True, exist_ok=True)
        os.chmod(age_key_path.parent, stat.S_IRWXU)  # 700

        # Generate keypair
        result = subprocess.run(
            ["age-keygen"],
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            print_error(f"Failed to generate age key: {result.stderr}")
            return 1

        # Write key with secure permissions
        age_key_path.write_text(result.stdout)
        os.chmod(age_key_path, stat.S_IRUSR | stat.S_IWUSR)  # 600

        print_success(f"Generated age keypair: {age_key_path}")

    # Extract public key for SOPS config
    key_content = age_key_path.read_text()
    public_key = None
    for line in key_content.splitlines():
        if line.startswith("# public key:"):
            public_key = line.split(": ", 1)[1].strip()
            break

    if not public_key:
        print_error("Could not extract public key from age key file")
        return 1

    print_info(f"Public key: {public_key}")

    # Create .sops.yaml configuration
    sops_config_path = PROJECT_ROOT / ".sops.yaml"
    if not sops_config_path.exists() or args.force:
        sops_config = f"""# SOPS configuration for MIRA secrets
# Generated by: mira-secrets init

creation_rules:
  - path_regex: secrets\\.enc\\.yaml$
    age: {public_key}
"""
        sops_config_path.write_text(sops_config)
        print_success(f"Created SOPS config: {sops_config_path}")
    else:
        print_info(f"SOPS config already exists: {sops_config_path}")

    # Create secrets template if not exists
    secrets_path = Path(args.secrets_path)
    if not secrets_path.exists() or args.force:
        _create_secrets_template(secrets_path, public_key)
        print_success(f"Created encrypted secrets template: {secrets_path}")
    else:
        print_info(f"Secrets file already exists: {secrets_path}")

    print("\n" + "=" * 50)
    print("  Setup complete!")
    print("=" * 50)
    print(f"\nNext steps:")
    print(f"  1. Edit secrets: python scripts/secrets_cli.py edit")
    print(f"  2. Validate:     python scripts/secrets_cli.py check")
    print(f"\nKey backup (IMPORTANT):")
    print(f"  Back up {age_key_path} securely - losing it means losing access to secrets!")

    return 0


def _create_secrets_template(secrets_path: Path, public_key: str) -> None:
    """Create an encrypted secrets template with placeholder values."""
    import yaml

    # Template with placeholder values
    template = {
        "providers": {
            "anthropic_key": "YOUR_ANTHROPIC_API_KEY_HERE",
            "anthropic_batch_key": "",
            "provider_key": "",
            "kagi_api_key": "",
            "openai_embeddings_key": "",
            "google_maps_api_key": "",
        },
        "database": {
            "service_url": "postgresql://mira_dbuser:changethisifdeployingpwd@localhost:5432/mira_service",
            "admin_url": "postgresql://mira_admin:changethisifdeployingpwd@localhost:5432/mira_service",
            "username": "mira_admin",
            "password": "changethisifdeployingpwd",
        },
        "services": {
            "valkey_url": "redis://localhost:6379/0",
        },
        "auth": {
            "jwt_secret": "GENERATE_A_SECURE_SECRET_HERE",
            "mira_api": "GENERATE_API_KEY_HERE",
        },
    }

    # Write unencrypted template first
    temp_path = secrets_path.with_suffix(".yaml.tmp")
    with open(temp_path, "w") as f:
        yaml.safe_dump(template, f, default_flow_style=False, sort_keys=False)

    # Encrypt with SOPS - use --filename-override to match .sops.yaml creation rule
    result = subprocess.run(
        [
            "sops", "-e",
            "--filename-override", str(secrets_path),  # Makes temp file match the rule
            "--output", str(secrets_path),
            str(temp_path)
        ],
        capture_output=True,
        text=True
    )

    # Clean up temp file
    temp_path.unlink(missing_ok=True)

    if result.returncode != 0:
        raise RuntimeError(f"Failed to encrypt secrets: {result.stderr}")

    os.chmod(secrets_path, stat.S_IRUSR | stat.S_IWUSR)  # 600


def cmd_edit(args: argparse.Namespace) -> int:
    """Edit secrets in $EDITOR (decrypts, edits, re-encrypts)."""
    secrets_path = Path(args.secrets_path)
    age_key_path = Path(args.age_key_path)

    if not secrets_path.exists():
        print_error(f"Secrets file not found: {secrets_path}")
        print_info("Run 'mira-secrets init' first to create the secrets file.")
        return 1

    if not age_key_path.exists():
        print_error(f"Age key not found: {age_key_path}")
        print_info("Run 'mira-secrets init' first to generate the age key.")
        return 1

    # Set environment for SOPS to find age key
    env = os.environ.copy()
    env["SOPS_AGE_KEY_FILE"] = str(age_key_path)

    # Use SOPS edit mode - decrypts to temp file, opens in $EDITOR, re-encrypts
    editor = os.environ.get("EDITOR", "vim")
    print(f"Opening secrets in {editor}...")
    print("(Save and close editor to re-encrypt)")

    result = subprocess.run(
        ["sops", str(secrets_path)],
        env=env
    )

    if result.returncode != 0:
        print_error("Failed to edit secrets")
        return 1

    print_success("Secrets updated and re-encrypted")

    # Validate after edit
    print("\nValidating updated secrets...")
    return cmd_check(args)


def cmd_check(args: argparse.Namespace) -> int:
    """Validate secrets configuration without starting MIRA."""
    print("Checking secrets configuration...\n")

    age_key_path = Path(args.age_key_path)
    secrets_path = Path(args.secrets_path)

    try:
        # Step 1: Check age key exists
        if not age_key_path.exists():
            raise FileNotFoundError(f"Age key not found: {age_key_path}")
        print_success("Age key found and valid")

        # Step 2: Decrypt secrets with SOPS
        if not secrets_path.exists():
            raise FileNotFoundError(f"Secrets file not found: {secrets_path}")

        env = os.environ.copy()
        env["SOPS_AGE_KEY_FILE"] = str(age_key_path)

        result = subprocess.run(
            ["sops", "-d", str(secrets_path)],
            env=env,
            capture_output=True,
            text=True
        )

        if result.returncode != 0:
            raise RuntimeError(f"Failed to decrypt secrets: {result.stderr}")

        import yaml
        secrets = yaml.safe_load(result.stdout)
        print_success("Secrets file decrypted successfully")

        # Step 3: Validate against schema
        with open(SCHEMA_PATH) as f:
            schema = yaml.safe_load(f)

        missing = []
        for key, spec in schema.get("secrets", {}).items():
            if spec.get("required", False):
                parts = key.split(".")
                value = secrets
                for part in parts:
                    if isinstance(value, dict):
                        value = value.get(part)
                    else:
                        value = None
                        break
                if not value:
                    missing.append(key)

        if missing:
            raise RuntimeError(f"Missing required secrets: {', '.join(missing)}")

        print_success("Schema validation passed")
        print("\nAll secrets checks passed. MIRA is ready to start.")
        return 0

    except FileNotFoundError as e:
        print_error(f"Missing file: {e}")
        print_info("Run 'mira-secrets init' to create required files.")
        return 1

    except RuntimeError as e:
        print_error(str(e))
        return 1

    except Exception as e:
        print_error(f"Unexpected error: {e}")
        return 1


def main() -> int:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        prog="mira-secrets",
        description="MIRA Secrets Management - SOPS-based encrypted secrets"
    )
    parser.add_argument(
        "--age-key-path",
        default=str(DEFAULT_AGE_KEY_PATH),
        help=f"Path to age private key (default: {DEFAULT_AGE_KEY_PATH})"
    )
    parser.add_argument(
        "--secrets-path",
        default=str(DEFAULT_SECRETS_PATH),
        help=f"Path to encrypted secrets file (default: {DEFAULT_SECRETS_PATH})"
    )

    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # init command
    init_parser = subparsers.add_parser("init", help="Initialize secrets management")
    init_parser.add_argument(
        "--force",
        action="store_true",
        help="Force regeneration of keys and config (WARNING: invalidates existing secrets)"
    )

    # edit command
    subparsers.add_parser("edit", help="Edit secrets in $EDITOR")

    # check command
    subparsers.add_parser("check", help="Validate secrets configuration")

    args = parser.parse_args()

    if args.command is None:
        parser.print_help()
        return 0

    commands = {
        "init": cmd_init,
        "edit": cmd_edit,
        "check": cmd_check,
    }

    return commands[args.command](args)


if __name__ == "__main__":
    sys.exit(main())

